### ISSUE TITLE
Wrong PubChem Compound ID in the source file

### ISSUE THREAD

**Issue by kevinxin90** [mkuhn/sider#4]
Hi,

I'm going through those files in http://sideeffects.embl.de/download/. Looks like the pubchem compound ID you guys put in those files are all wrong.

For example, 'Amoxicillin' should correspond to CID2171. However, in the source file, you put it as CID100002171, while this CID10000217 refers to a totally different compound https://pubchem.ncbi.nlm.nih.gov/compound/100002171. Moreover, 'Amoxicillin' is not a single edge case in SIDER. Looks like the file arbitrarily added '100000*' to all the pubchem compound IDs in SIDER.

**Comment by mkuhn** [comment]
These are not PubChem ids, these are STITCH 4 ids. See e.g. the STITCH 5 README:


```
CIDs / CID0... - this is a stereo-specific compound, and the suffix is the 
PubChem compound id.

CIDm / CID1... - this is a "flat" compound, i.e. with merged stereo-isomers
The suffix (without the leading "1") is the PubChem compound id.
```

**Comment by kevinxin90** [comment]
Great! Thanks for the clarification!
