### ISSUE TITLE
Access permission to SIDER Side Effect Resource

### ISSUE THREAD

**Issue by JeanCoquet** [mkuhn/sider#6]
Hello,

I am trying to use the SIDER side effects interface and I have access permission error when I click on label information detail.
Below my error:
```
Forbidden

You don't have permission to access /media/pdf/fda/20103s023,20605s007,20781s007lbl/annotated.html on this server.
```

Thanks,
Jean

**Comment by mkuhn** [comment]
I'm sorry, I moved some data and didn't realise that it would affect SIDER. We're working on it!

**Comment by mkuhn** [comment]
Ok, it's back. Thanks for reporting the issue!

**Comment by JeanCoquet** [comment]
Thank you!
